import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../../');
const schemaPath = path.resolve(__dirname, '../../config.schema.json');
const readmePath = path.resolve(rootDir, 'README.md');
const envExamplePath = path.resolve(rootDir, '.env.example');

async function main() {
  const schema = JSON.parse(await fs.readFile(schemaPath, 'utf8'));
  
  // 1. Generate .env.example
  let envContent = '# Environment Configuration Example\n# This file is automatically generated from config.schema.json.\n\n';
  
  for (const [key, prop] of Object.entries(schema.properties)) {
    const isRequired = (schema.required || []).includes(key);
    envContent += `# ${prop.description || ''}\n`;
    envContent += `# Type: ${prop.type}${isRequired ? ' (Required)' : ''}\n`;
    
    let defaultValue = prop.default !== undefined ? prop.default : '';
    envContent += `${key}=${defaultValue}\n\n`;
  }
  
  await fs.writeFile(envExamplePath, envContent, 'utf8');
  console.log(`Generated .env.example`);

  // 2. Update README.md
  let readme = await fs.readFile(readmePath, 'utf8');
  
  let markdownTable = '| Variable | Type | Required | Default | Description |\n';
  markdownTable += '| --- | --- | --- | --- | --- |\n';
  
  for (const [key, prop] of Object.entries(schema.properties)) {
    const isRequired = (schema.required || []).includes(key) ? 'Yes' : 'No';
    const defaultValue = prop.default !== undefined ? `\`${prop.default}\`` : '';
    const desc = prop.description || '';
    markdownTable += `| \`${key}\` | \`${prop.type}\` | ${isRequired} | ${defaultValue} | ${desc} |\n`;
  }
  
  const startMarker = '<!-- CONFIG_START -->';
  const endMarker = '<!-- CONFIG_END -->';
  
  const startIndex = readme.indexOf(startMarker);
  const endIndex = readme.indexOf(endMarker);
  
  if (startIndex !== -1 && endIndex !== -1) {
    readme = readme.substring(0, startIndex + startMarker.length) + '\n\n' + markdownTable + '\n' + readme.substring(endIndex);
    await fs.writeFile(readmePath, readme, 'utf8');
    console.log(`Updated README.md Configuration section`);
  } else {
    console.warn('Could not find <!-- CONFIG_START --> and <!-- CONFIG_END --> in README.md');
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
