
import { Create, Edit, SimpleForm, type CreateProps, type EditProps, type RaRecord } from 'react-admin';
import { useAutoFormSetup } from '../hooks/useAutoFormSetup';

/**
 * Props for the AutoCreate component.
 * Inherits all standard React-Admin CreateProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoCreateProps<RecordType extends RaRecord = RaRecord> extends Omit<CreateProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders a create form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoCreate = <RecordType extends RaRecord = RaRecord>(props: AutoCreateProps<RecordType>) => {
  const { resourceName, layoutConfig, CustomLayout, contentNodes, errorSummary } = useAutoFormSetup(props.resource, 'create');

  if (CustomLayout) {
    return (
      <Create {...props}>
        <CustomLayout resourceName={resourceName} layoutConfig={layoutConfig} isCreate={true}>
          {errorSummary}
          {contentNodes}
        </CustomLayout>
      </Create>
    );
  }

  return (
    <Create {...props}>
      <SimpleForm>
        {errorSummary}
        {contentNodes}
      </SimpleForm>
    </Create>
  );
};

/**
 * Props for the AutoEdit component.
 * Inherits all standard React-Admin EditProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoEditProps<RecordType extends RaRecord = RaRecord> extends Omit<EditProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders an edit form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoEdit = <RecordType extends RaRecord = RaRecord>(props: AutoEditProps<RecordType>) => {
  const { resourceName, layoutConfig, CustomLayout, contentNodes, errorSummary, idInput } = useAutoFormSetup(props.resource, 'edit');

  if (CustomLayout) {
    return (
      <Edit {...props}>
        <CustomLayout resourceName={resourceName} layoutConfig={layoutConfig} isCreate={false}>
          {errorSummary}
          {idInput}
          {contentNodes}
        </CustomLayout>
      </Edit>
    );
  }

  return (
    <Edit {...props}>
      <SimpleForm>
        {errorSummary}
        {idInput}
        {contentNodes}
      </SimpleForm>
    </Edit>
  );
};
