import { List, Datagrid, DatagridRow, useRecordContext, TextField, type ListProps, type RaRecord } from 'react-admin';
import { useSpec } from '../core/SpecContext';
import { renderPrecomputedField, type PrecomputedFieldDescriptor } from './SchemaToFieldMapper';
import { resolveRecordLabel } from './AccessibilityUtils';

const CustomDatagridRow = (props: any) => {
  const { resourceName, manifestPrimaryField, specSchema, ...rest } = props;
  const record = useRecordContext(props);
  const label = record ? resolveRecordLabel(record, resourceName, manifestPrimaryField, specSchema) : undefined;
  return <DatagridRow {...rest} aria-label={label} />;
};

/**
 * Props for the AutoList component.
 * Inherits all standard React-Admin ListProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoListProps<RecordType extends RaRecord = RaRecord> extends Omit<ListProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders a list of items based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoList = <RecordType extends RaRecord = RaRecord>(props: AutoListProps<RecordType>) => {
  const { uiManifest, spec } = useSpec();
  const resourceName = props.resource || '';
  const precomputedResource = uiManifest?.resources?.[resourceName];
  const precomputedListFields = precomputedResource?.listFields as PrecomputedFieldDescriptor[] | undefined;
  const manifestPrimaryField = precomputedResource?.primaryField;
  const specSchema = spec?.components?.schemas?.[resourceName];

  if (precomputedListFields && precomputedListFields.length > 0) {
    const idField = precomputedListFields.find(field => field.source === 'id');
    const nonIdFields = precomputedListFields.filter(field => field.source !== 'id');

    return (
      <List {...props}>
        <Datagrid 
          rowClick="edit" 
          row={<CustomDatagridRow resourceName={resourceName} manifestPrimaryField={manifestPrimaryField} specSchema={specSchema} />}
        >
          {idField ? renderPrecomputedField(idField, `${resourceName}.id`) : <TextField source="id" />}
          {nonIdFields.map((field, index) =>
            renderPrecomputedField(field, `${resourceName}.${field.source || index}`)
          )}
        </Datagrid>
      </List>
    );
  }

  return (
    <List {...props}>
      <Datagrid row={<CustomDatagridRow resourceName={resourceName} manifestPrimaryField={manifestPrimaryField} specSchema={specSchema} />}>
        <TextField source="id" />
      </Datagrid>
    </List>
  );
};
