
import React from 'react';
import { Create, Edit, SimpleForm, TextInput, type CreateProps, type EditProps, type RaRecord } from 'react-admin';
import { useSpec } from '../core/SpecContext';
import { renderInput, type PrecomputedInputDescriptor } from './SchemaToFieldMapper';
import { SchemaErrorSummary } from './SchemaErrorSummary';
import { useLayoutRegistry } from '../core/LayoutRegistry';

/**
 * Props for the AutoCreate component.
 * Inherits all standard React-Admin CreateProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoCreateProps<RecordType extends RaRecord = RaRecord> extends Omit<CreateProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders a create form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoCreate = <RecordType extends RaRecord = RaRecord>(props: AutoCreateProps<RecordType>) => {
  const { uiManifest } = useSpec();
  const { getLayout } = useLayoutRegistry();
  const resourceName = props.resource || '';
  
  const precomputedResource = uiManifest?.resources?.[resourceName];
  const layoutId = precomputedResource?.createLayout || precomputedResource?.layout;
  const layoutConfig = precomputedResource?.createLayoutConfig || precomputedResource?.layoutConfig;
  const CustomLayout = layoutId ? getLayout(layoutId) : undefined;

  const precomputedNodes = precomputedResource?.createForm as PrecomputedInputDescriptor[] | undefined;
  let contentNodes: React.ReactNode[] = [];
  if (precomputedNodes && precomputedNodes.length > 0) {
    contentNodes = precomputedNodes.map((node, index) => 
      renderInput(node, `${resourceName}.${node.source || index}`)
    );
  } else {
    contentNodes = [<TextInput key="id" source="id" />];
  }

  const errorSummary = <SchemaErrorSummary key="error-summary" resourceName={resourceName} isCreate={true} />;

  if (CustomLayout) {
    return (
      <Create {...props}>
        <CustomLayout resourceName={resourceName} layoutConfig={layoutConfig} isCreate={true}>
          {errorSummary}
          {contentNodes}
        </CustomLayout>
      </Create>
    );
  }

  return (
    <Create {...props}>
      <SimpleForm>
        {errorSummary}
        {contentNodes}
      </SimpleForm>
    </Create>
  );
};

/**
 * Props for the AutoEdit component.
 * Inherits all standard React-Admin EditProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoEditProps<RecordType extends RaRecord = RaRecord> extends Omit<EditProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders an edit form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoEdit = <RecordType extends RaRecord = RaRecord>(props: AutoEditProps<RecordType>) => {
  const { uiManifest } = useSpec();
  const { getLayout } = useLayoutRegistry();
  const resourceName = props.resource || '';

  const precomputedResource = uiManifest?.resources?.[resourceName];
  const layoutId = precomputedResource?.editLayout || precomputedResource?.layout;
  const layoutConfig = precomputedResource?.editLayoutConfig || precomputedResource?.layoutConfig;
  const CustomLayout = layoutId ? getLayout(layoutId) : undefined;

  const precomputedNodes = precomputedResource?.editForm as PrecomputedInputDescriptor[] | undefined;
  let contentNodes: React.ReactNode[] = [];
  if (precomputedNodes && precomputedNodes.length > 0) {
    contentNodes = precomputedNodes.map((node, index) => 
      renderInput(node, `${resourceName}.${node.source || index}`)
    );
  } else {
    contentNodes = [<TextInput key="id-fallback" source="id" />];
  }

  const errorSummary = <SchemaErrorSummary key="error-summary" resourceName={resourceName} isCreate={false} />;
  const idInput = <TextInput key="id-disabled" source="id" disabled />;

  if (CustomLayout) {
    return (
      <Edit {...props}>
        <CustomLayout resourceName={resourceName} layoutConfig={layoutConfig} isCreate={false}>
          {errorSummary}
          {idInput}
          {contentNodes}
        </CustomLayout>
      </Edit>
    );
  }

  return (
    <Edit {...props}>
      <SimpleForm>
        {errorSummary}
        {idInput}
        {contentNodes}
      </SimpleForm>
    </Edit>
  );
};
