import { List, Datagrid, TextField, useListContext, type ListProps, type RaRecord } from 'react-admin';
import { useSpec } from '../core/SpecContext';
import { renderPrecomputedField, type PrecomputedFieldDescriptor } from './SchemaToFieldMapper';
import { VisuallyHidden, getStatusMessage } from './AccessibilityUtils';

const ListAccessibilityWrapper = ({ children }: { children: React.ReactNode }) => {
  const { isLoading, data, total } = useListContext();
  
  let announcement = '';
  if (isLoading) {
    announcement = getStatusMessage('loading');
  } else if (data) {
    if (data.length === 0 || total === 0) {
      announcement = getStatusMessage('empty');
    } else {
      announcement = getStatusMessage('loaded', total || data.length);
    }
  }

  return (
    <>
      <VisuallyHidden aria-live="polite">
        {announcement}
      </VisuallyHidden>
      {children}
    </>
  );
};

/**
 * Props for the AutoList component.
 * Inherits all standard React-Admin ListProps.
 * 
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoListProps<RecordType extends RaRecord = RaRecord> extends Omit<ListProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders a list of items based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param {AutoListProps<RecordType>} props - Component props
 */
export const AutoList = <RecordType extends RaRecord = RaRecord>(props: AutoListProps<RecordType>) => {
  const { uiManifest } = useSpec();
  const resourceName = props.resource || '';
  const precomputedResource = uiManifest?.resources?.[resourceName];
  const precomputedListFields = precomputedResource?.listFields as PrecomputedFieldDescriptor[] | undefined;

  if (precomputedListFields && precomputedListFields.length > 0) {
    const idField = precomputedListFields.find(field => field.source === 'id');
    const nonIdFields = precomputedListFields.filter(field => field.source !== 'id');

    return (
      <List {...props}>
        <ListAccessibilityWrapper>
          <Datagrid rowClick="edit">
            {idField ? renderPrecomputedField(idField, `${resourceName}.id`) : <TextField source="id" />}
            {nonIdFields.map((field, index) =>
              renderPrecomputedField(field, `${resourceName}.${field.source || index}`)
            )}
          </Datagrid>
        </ListAccessibilityWrapper>
      </List>
    );
  }

  return (
    <List {...props}>
      <ListAccessibilityWrapper>
        <Datagrid>
          <TextField source="id" />
        </Datagrid>
      </ListAccessibilityWrapper>
    </List>
  );
};
