
import { Create, Edit, type CreateProps, type EditProps, type RaRecord } from 'react-admin';
import { useAutoFormSetup } from '../hooks/useAutoFormSetup';

/**
 * Props for the AutoCreate component.
 * Inherits all standard React-Admin CreateProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoCreateProps<RecordType extends RaRecord = RaRecord> extends Omit<CreateProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders a create form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoCreate = <RecordType extends RaRecord = RaRecord>(props: AutoCreateProps<RecordType>) => {
  const { formContent } = useAutoFormSetup(props.resource, 'create');

  return (
    <Create {...props}>
      {formContent}
    </Create>
  );
};

/**
 * Props for the AutoEdit component.
 * Inherits all standard React-Admin EditProps.
 * @template RecordType - The API model type generated by Orval.
 */
export interface AutoEditProps<RecordType extends RaRecord = RaRecord> extends Omit<EditProps<RecordType>, 'resource'> {
    /**
     * Optional explicit resource name. Usually injected by React-Admin.
     */
    resource?: string;
}

/**
 * Automatically renders an edit form based on the OpenAPI schema and manifest.
 * @template RecordType - The Orval model representing this resource
 * @param props - Component props
 */
export const AutoEdit = <RecordType extends RaRecord = RaRecord>(props: AutoEditProps<RecordType>) => {
  const { formContent } = useAutoFormSetup(props.resource, 'edit');

  return (
    <Edit {...props}>
      {formContent}
    </Edit>
  );
};
