import React, { useCallback, useMemo } from 'react';
import { UnifiedSchemaWalker } from '@duckdeploy/openapi';
import type { OpenAPIV3 } from 'openapi-types';

/**
 * Wraps fields generated by the schema mapper to provide schema-aware parsing and formatting logic.
 * Enforces real-time type coercion and consistent handling of empty values in the form state.
 * @param props The wrapper properties.
 * @param props.schemaNode The schema definition or precomputed descriptor for the field.
 * @param props.children The render prop that provides `parse` and `format` interceptors.
 * @returns The wrapped component.
 */
export const SchemaLifecycleWrapper = ({
  schemaNode,
  children,
}: {
  schemaNode: any;
  children: (interceptors: { parse: (val: any) => any; format: (val: any) => any }) => React.ReactNode;
}) => {
  const schema = useMemo(() => {
    if (schemaNode && 'kind' in schemaNode && !('type' in schemaNode)) {
      const kind = schemaNode.kind as string;
      const type = kind === 'number' || kind === 'integer' ? 'number' 
                 : kind === 'boolean' ? 'boolean' 
                 : kind === 'array' ? 'array'
                 : kind === 'object' ? 'object'
                 : 'string';
      return { ...schemaNode, type } as OpenAPIV3.SchemaObject;
    }
    return schemaNode as OpenAPIV3.SchemaObject;
  }, [schemaNode]);

  const parse = useCallback((val: any) => {
    const walker = new UnifiedSchemaWalker(
      { visitNode: (_, defaultVisit) => defaultVisit() },
      { walkPayload: true }
    );
    return walker.walk(schema, val);
  }, [schema]);

  const format = useCallback((val: any) => {
    if (val === null || val === undefined) {
      return '';
    }
    return val;
  }, []);

  return <>{children({ parse, format })}</>;
};
